name: magnet
description: A scraping engine for Daystar University Portal Endpoints
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  dotenv: ^4.1.0
  html: ^0.15.4
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
